
## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd 
install:
  - ./pkg-build.sh install_deps
